<a href="https://colab.research.google.com/github/angajs/SPMNWPU/blob/main/Python_Colab_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Number of classes - do not change unless the data changes
num_classes = 10


In [ ]:
batch_size = 64
epochs = 24
training: 60000


In [ ]:
img_rows, img_cols = 28, 28


In [ ]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [16]:
x_test.shape

(10000, 28, 28)

In [14]:
len(y_train)

60000

In [15]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [17]:
x_train.shape[0]

60000

In [18]:
x_train = x_train.reshape(x_train.shape[0],img_rows, img_cols,1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols,1)
input_shape = (img_rows, img_cols, 1)



In [19]:
input_shape

(28, 28, 1)

In [20]:
x_train.shape

(60000, 28, 28, 1)

In [23]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255.
x_test  /= 255.
print('x_train shape:', x_train.shape)
print( 'x_test shape:', x_test. shape)
print(y_train[0:3])

x_train shape: (60000, 28, 28, 1)
x_test shape: (10000, 28, 28, 1)
[9 0 0]


In [24]:
# convert class vectors to binary class matrices. One-hot encoding
# 3 => 0001000000 and 1 = 01000 0 0000
y_train = tf. keras. utils. to_categorical (y_train, num_classes)
y_test = tf. keras.utils.to_categorical(y_test, num_classes)
print(y_train[0:2]) # verify one-hot encoding

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
# Define the model
model = Sequential()

In [26]:
num_classes

10

In [33]:
# Create a CNN to classify the images
model.add (Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=input_shape))
model.add (MaxPooling2D(pool_size=(2, 2)))
model.add (Conv2D(32, kernel_size=(3, 3), activation='relu'))
model.add (MaxPooling2D(pool_size=(2, 2)))
model. add (Flatten())
model. add (Dense(128, activation='relu'))
model. add (Dense(64, activation= 'relu'))
#model. add (Dropout (0.5))
model. add (Dense(num_classes,activation='softmax'))

In [36]:
#define compile to minimize categorical loss, use lada delta optimized, and optimize to maximizing accuracy
model. compile(loss=keras.losses.categorical_crossentropy,
optimizer=keras.optimizers.Adam(),
metrics=['accuracy'])
#Train the model and test/validate the mode with the test data after each cycle (epoch) through the training data
#Return history of loss and accuracy for each epoch
hist = model.fit(x_train, y_train,
            batch_size=batch_size, epochs=epochs,
            verbose=1,
            validation_data=(x_test, y_test))

Epoch 1/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 42s 43ms/step - accuracy: 0.7261 - loss: 0.7766 - val_accuracy: 0.8573 - val_loss: 0.4016
Epoch 2/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 39s 41ms/step - accuracy: 0.8714 - loss: 0.3557 - val_accuracy: 0.8747 - val_loss: 0.3455
Epoch 3/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 39s 41ms/step - accuracy: 0.8865 - loss: 0.3046 - val_accuracy: 0.8789 - val_loss: 0.3250
Epoch 4/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 40s 42ms/step - accuracy: 0.9020 - loss: 0.2671 - val_accuracy: 0.8880 - val_loss: 0.3063
Epoch 5/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 40s 42ms/step - accuracy: 0.9091 - loss: 0.2447 - val_accuracy: 0.8984 - val_loss: 0.2768
Epoch 6/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 39s 40ms/step - accuracy: 0.9171 - loss: 0.2253 - val_accuracy: 0.9020 - val_loss: 0.2644
Epoch 7/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 40s 42ms/step - accuracy: 0.9222 - loss: 0.2042 - val_accuracy: 0.9080 - val_loss: 0.2608
Epoch 8/24
938/938 ━━━━━━━━━━━━━━━━━━━━ 41s 42ms/step - accuracy: 0.9287 - loss: 0.1900 - 

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)                    │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 11, 11, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 5, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 800)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         102,528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 363,008 (1.38 MB)

 Trainable params: 121,002 (472.66 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 242,006 (945.34 KB)